# Generated by Django 3.0.3 on 2020-05-14 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20200514_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OUT OF DELIVERED', 'OUT OF DELIVERED'), ('PENDING', 'PENDING'), ('DELIVERED', 'DELIVERED')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('OUTDOOR', 'OUTDOOR'), ('INDOOR', 'INDOOR')], max_length=200, null=True),
        ),
    ]
